apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: turbonomic
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/mikelo/t8c-install
    path: operator/deploy/argocd/resources/
    targetRevision: argocd
    kustomize:
      patches:
        - patch: |-
            - op: replace
              path: /spec/targetNamespaces
              value: ["turbonomic"]
          target:
            kind: OperatorGroup
            name: turbonomic
        - patch: |-
            - op: replace
              path: /spec/global/securityContext/fsGroup
              value: 1000730000
            - op: replace
              path: /spec/global/tag
              value: 8.16.0              
          target:
            kind: Xl
            name: xl-release              
  destination:
    namespace: turbonomic
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

