apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: t8c-operator
  # namespace: openshift-gitops
subjects:
- kind: ServiceAccount
  name: t8c-operator
  namespace: openshift-gitops
roleRef:
  kind: Role
  name: t8c-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: t8c-operator
  # namespace: openshift-gitops
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - pods
  - pods/exec
  - secrets
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  - virtualservices
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - '*'
- apiGroups:
    - route.openshift.io
  resources:
    - routes
    - routes/custom-host
  verbs:
    - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: t8c-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  # generateName: turbonomic-
  name: turbonomic
  # namespace: openshift-gitops-operator
spec:
  targetNamespaces:
  - turbonomic
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: t8c-certified
  # namespace: openshift-gitops-operator 
spec:
  channel: stable
  name: t8c-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace